### ISSUE TITLE
imp no longer exists in 3.1

### ISSUE THREAD

**Issue by clausing** [obsidianforensics/unfurl#195]
**Description**
Import from imp fail since imp is no longer supported in python 3.12. Generates lots of the the following error(s)

```[2024-02-09 19:45:18,079] ERROR in core: Failed to import parse_mac_addr: No module named 'imp'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/unfurl/core.py", line 319, in run_plugins
    parser = importlib.import_module(f'unfurl.parsers.{unfurl_parser}')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/usr/local/lib/python3.12/site-packages/unfurl/parsers/parse_mac_addr.py", line 15, in <module>
    import maclookup
  File "/usr/local/lib/python3.12/site-packages/maclookup/__init__.py", line 5, in <module>
    from .api_client import ApiClient
  File "/usr/local/lib/python3.12/site-packages/maclookup/api_client.py", line 2, in <module>
    from future.standard_library import install_aliases
  File "/usr/local/lib/python3.12/site-packages/future/standard_library/__init__.py", line 65, in <module>
    import imp
ModuleNotFoundError: No module named 'imp'```

**Comment by obsidianforensics** [comment]
I believe this is caused by the `maclookup` package, which looks like it hasn't been updated since 2018(!) and doesn't work well with Python 3.12. I'll look at finding a different way to provide this functionality.

**Comment by eljeffeg** [comment]
Speaking of maclookup, we ran into issues using the pip install as it didn't include the maclookup requirement.  Maybe the requirement.txt should include all modules and then have other files if you want a slim version?

**Comment by eljeffeg** [comment]
Perhaps doing this might avoid it as a main application requirement by only importing it if it's actually used.

```
elif node.data_type == 'mac-address' and unfurl.api_keys.get('macaddress_io') and unfurl.remote_lookups:
        import maclookup
        client = maclookup.ApiClient(unfurl.api_keys.get('macaddress_io'))
```

**Comment by eljeffeg** [comment]
Looks like there are several alternatives or could probably just use `requests` and hit the REST API directly.

**Comment by obsidianforensics** [comment]
Thanks for raising, and for the solution ideas. I found a different, offline lookup package and switched to that.
